#! /usr/bin/env python

obj = bld.new_task_gen('cc', 'program')

obj.env['CCFLAGS'] = ''
obj.source='main.c rdbdiff.c ../rdb.c ../ut.c bytediff.c ../rahash/crc16.c'
#obj.env['CCFLAGS'].append('-DRADARE_CORE=0')

obj.includes = '. ../'

obj.target = 'radiff'
