.Dd January 6, 2007
.Dt RSC 1
.Os
.Sh NAME
.Nm rsc
.Nd Helper utility for launching radare libexec scripts
.Sh SYNOPSIS
.Nm rsc
.Op Fl -list|-h
.Op scriptname
.Op -h
.Sh DESCRIPTION
rsc allows you to execute multiple utilities included with radare placed in ~/.radare/scripts or ${prefix}/libexec/radare/.
.Bl -tag -width Fl
.It Fl -list
List all available scripts found in the libexec directory.
.It Fl h
Show usage help message.
.Sh SEE ALSO
.Pp
.Xr radiff(1) ,
.Xr hasher(1) ,
.Xr rabin(1) ,
.Xr radare(1) ,
.Xr rfile(1) ,
.Xr rasc(1) ,
.Xr rasm(1) ,
.Xr xc(1) ,
.Xr xrefs(1)
.Sh AUTHORS
.Pp
pancake <pancake@youterm.com>
.Pp
