#! /usr/bin/env python

#plug_io = bld.new_task_gen('cc', 'staticlib')
plug_io        = bld.create_obj('cc', 'staticlib')
plug_io.target = 'plug-io'

plug_io.source = 'gdb.c winedbg.c gdbx.c haret.c posix.c mmap.c remote.c shm.c socket.c gxemul.c'

#plug_io.env['CCFLAGS'].append('-I..')
plug_io.includes = '../..'

#plug_io.packages='gtk+-2.0'
