NAME=r_asm
OBJ=asm.o arch/x86/asm.o

# udis86
OBJ+=arch/x86/udis86/syn.o
OBJ+=arch/x86/udis86/input.o
OBJ+=arch/x86/udis86/udis86.o
OBJ+=arch/x86/udis86/decode.o
OBJ+=arch/x86/udis86/syn-att.o
OBJ+=arch/x86/udis86/itab.o
OBJ+=arch/x86/udis86/syn-intel.o

# olly
#OBJ+=arch/x86/ollyasm/disasm.o


include ../rules.mk
