/* This vapi has been manually generated by me */
[CCode (cheader_filename="r_socket.h", cprefix="r_socket", lower_case_cprefix="r_socket_")]
namespace Radare.Socket {
	int ready(int fd, int secs, int usecs);
	int read(int fd, out uint8[] buf, int len);
	int write(int fd, ref uint8[] buf, int len);
	int connect(string host, int port);
	int listen(int port);
	int fgets(int fd, out uint8[] buf, int len);
	int printf(int fd, string str, ...);
	int accept(int fd);
}
