#! /usr/bin/env python

obj = bld.create_obj('cc', 'staticlib')
obj.sources = 'arch/i386.c arch/i386-bp.c arch/i386-hack.c'
obj.find_sources_in_dirs('.')
obj.find_sources_in_dirs('unix')
obj.includes = '.. .'

obj.target = 'radare-dbg.a'
#obj.uselib = ''
#obj.packages='gtk+-2.0'
