#! /usr/bin/env python

obj = bld.new_task_gen('cc', 'staticlib')
obj.target  = 'debugger'
obj.includes = '../arch ..'
obj.source  = ' bp.c close.c debug.c events.c lseek.c mem.c open.c parser.c procs.c signal.c system.c thread.c wp.c'
# XXX UNUSED FILES : watchpoint.c ptrace.c, libps2fd.c dosdebug.c # must be removed
cpu = bld.env['CPU']
#obj.source += ' arch/i386.c arch/i386-bp.c arch/i386-hack.c'
obj.source += ' arch/%s.c arch/%s-bp.c arch/%s-hack.c'%(cpu,cpu,cpu)

if bld.env['OS'] == 'Darwin':
	obj.find_sources_in_dirs('darwin')
else:
	obj.find_sources_in_dirs('unix')
