OBJ=radare2.o
BIN=radare2
LIBS=../*.o \
  ../../config/*.a \
  ../../cons/*.a \
  ../../line/*.a \
  ../../io/*.a \
  ../../cmd/*.a \
  ../../util/*.a \
  ../../print/*.a \
  ../../flags/*.a

include ../../tests.mk
