#! /usr/bin/env python

obj = bld.new_task_gen('cc', 'program')
obj.target = 'rabin'
obj.source='rabin.c dietelf.c'
obj.env.append_value('CCFLAGS','-DRADARE_CORE')
obj.env.append_value('LINKFLAGS','-ldl')
