#! /usr/bin/env python

obj = bld.new_task_gen('cc', 'program')
obj.target = 'rabin'
obj.source='rabin.c dietelf.c dietelf64.c dietpe.c'
obj.env.append_value('CCFLAGS','-DRADARE_CORE')
if bld.env['OS'] == 'Linux':
	obj.env.append_value('LINKFLAGS','-ldl')
