#!/bin/sh
PRG=$1

if [ -z "${PRG}" ]; then
	echo "Usage: rsc elf-prg-maps \${FILE}"
	echo "=> Nice for core files!"
else
	readelf -l ${PRG} | grep 0x | sed -e 's,LOAD,prg_,g' -e 's,NOTE,note_,g' |grep -e prg -e note | awk '{print "f "$1""$3" @ "$2"\nf "$1""$3"_end @ "$2"+"$5}'
fi
