#!/bin/sh
#
# author: pof <eslack.org>
#

if [ -z $1 ]; then
	echo "Usage: flag [file]">/dev/stderr
	exit 1
fi

FILE=$1
type=`file $FILE |awk '{print $2}'`

echo "Automagically flagging $FILE" >/dev/stderr

case "$type" in
	"PE")
		rsc syms-pe-flag ${FILE}
		rsc strings-pe-flag ${FILE}
	;;

	"ELF")
		rsc flag-sections ${FILE}
		rsc syms-dbg-flag ${FILE}
		## are we being called from debugger??
		#if [ -n "$DPID" ]; then
		#	rsc syms-dbg-flag ${FILE}
		#else
		#	rsc syms-flag ${FILE}
		#fi
		rsc strings-flag ${FILE}
		rsc syscall-flag ${FILE}
	;;
esac

echo "s entrypoint"
