#!/usr/bin/env perl
#
# Binary diff utility for radare
#
# NOTES
#  - allow to handle big files with low memory footprint. ha ha ha
#  - we have to do an adaptative diff method using bytediff+bindiff
#
# author:  pancake <pancake@youterm.com>
# license: gpl (>=2)
#

my $a = $ARGV[0];
my $b = $ARGV[1];
my $ws = 1024*1024*5; # warning size (5M)

die "Usage: bindiff [a-file] [b-file]\n".
    "f.e.:  bindiff a.out b.out | rsc bdcolor 3\n"
	if ($a eq "" or $b eq "" or $a eq "-h");

sub domybest {
	unlink $tmpa;
	unlink $tmpb;
	exit 0;
}

$SIG{INT}=\&domybest;

sub bin_to_hex_column {
	my($filename, $column) = @_;
	open LOG, '>', $column || die "Cannot open $column";
	open FD, '<', $filename || die "Cannot open $filename";
  	for(;;) {
		last if 0 == read(FD, $buf, 1);
		$str = sprintf("%02x\n", ord($buf));
		print LOG $str;
	}
	close LOG;
	close FD;
}

die "Cannot read any of these files.\n" unless (-r $a and -r $b);

print STDERR "Warning: Probably so big files to handle with gnu diff, try radiff -b\n"
	if (-s $a > $ws or -s $b > $ws);

$tmpa="/tmp/.a.$$.".int rand(0xfef);
bin_to_hex_column($a, $tmpa);
$tmpb="/tmp/.b.$$.".int rand(0xefe);
bin_to_hex_column($b, $tmpb);

system("diff -yW 15 $tmpa $tmpb"); # | rsc bdcolor 3

domybest;
