#!/bin/sh
#
# pancake <youterm.com>

FILE=$1
ADDR=$2
if [ -z "${ADDR}" ]; then
	echo "Usage: dwarf-addr [a.out] [addr]"
	exit 1
fi

if [ ! "`echo ${ADDR}| grep 0x`" ]; then
	ADDR=`rax ${ADDR}`
fi

FL=`rsc dwarf-at $FILE ${ADDR}`
if [ -z "`echo $FL| grep ??`" ]; then
#	[ -n "`echo $FL` | grep Binary" ] && exit
	FILE=`echo $FL|cut -d : -f 1`
	LINE=`echo $FL|cut -d : -f 2`
	nl $FILE | grep -e " $LINE" | head -n 1
fi
