#!/bin/sh
#
# pancake <youterm.com>

FILE=$1
ADDR=$2
if [ -z "${ADDR}" ]; then
	echo "Usage: dwarf-addr [file] [æddr]"
	exit 1
fi

if [ ! "`echo ${ADDR}| grep 0x`" ]; then
	ADDR=`xc ${ADDR}`
fi

FL=`addr2line -e $FILE ${ADDR}`
if [ ! "`echo $FL| grep ??`" ]; then
	[ -n "`echo $FL` | grep Binary" ] && exit
	FILE=`echo $FL|cut -d : -f 1`
	LINE=`echo $FL|cut -d : -f 2`
	nl $FILE | grep -e " $LINE" |head -n 1
fi
