#!/usr/bin/env perl
#
# Dump a radare script that flags all symbols at it's _MEMORY_ offset.
#
# author: pancake
#

my $target = $ARGV[0];

if (( $target eq "" ) || ( $target eq "-h" )) {
	print STDERR "Usage: rsc syms-dbg-flag [file] > file.syms.flags\n";
	exit 1;
}



if ( `uname`=~/Darwin/ ) {
 	system("otool -tv $target|grep -C 1 -e : |grep -v / | awk '{if (/:/){label=\$1;gsub(\":\",\"\",label);next}if (label!=\"\"){print \"f sym\"label\" @ 0x\"\$1;label=\"\"}}'\n");
	#rabin -E $target
	exit 1;
}

my @syms = split(/\n/,qx(rsc syms $target));
for my $i (0 .. @syms) {
	if (!($syms[$i] =~ /fs? [imp_|sym_]/)) {
		my ($addr, $name) = split(/ /,$syms[$i]);
		$name =~ s/@.*//g;
		next if ($name eq "");
		print "fs symbols\n";
		printf "f sym_$name @ $addr\n";
	} else {
		print $syms[$i],"\n";
	}
}
print STDERR @syms." symbols added.\n";
