#! /usr/bin/env python

obj = bld.create_obj('cc', 'program')
#obj.env['CCFLAGS'] = ''
#LIL_ENDIAN="1"
#obj.env['CCFLAGS'].append('-DLIL_ENDIAN="'+LIL_ENDIAN+'"')
obj.env.append_value('LINKFLAGS','-lm')
obj.source='hasher.c crc16.c crc32.c entropy.c hash.c hamdist.c md4.c md5c.c sha1.c sha2.c'

obj.target = 'hasher'
