/* SeekTo.c generated by valac, the Vala compiler
 * generated from SeekTo.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <stdio.h>


#define TYPE_SEEK_TO (seek_to_get_type ())
#define SEEK_TO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SEEK_TO, SeekTo))
#define SEEK_TO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SEEK_TO, SeekToClass))
#define IS_SEEK_TO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SEEK_TO))
#define IS_SEEK_TO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SEEK_TO))
#define SEEK_TO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SEEK_TO, SeekToClass))

typedef struct _SeekTo SeekTo;
typedef struct _SeekToClass SeekToClass;
typedef struct _SeekToPrivate SeekToPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define __g_list_free_g_free0(var) ((var == NULL) ? NULL : (var = (_g_list_free_g_free (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _SeekTo {
	GtkDialog parent_instance;
	SeekToPrivate * priv;
};

struct _SeekToClass {
	GtkDialogClass parent_class;
};

struct _SeekToPrivate {
	GtkComboBoxEntry* cbe;
	char* selected;
	GList* variables;
};


static gpointer seek_to_parent_class = NULL;

GType seek_to_get_type (void);
#define SEEK_TO_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_SEEK_TO, SeekToPrivate))
enum  {
	SEEK_TO_DUMMY_PROPERTY
};
static void _g_list_free_g_free (GList* self);
static void seek_to_init_variables (SeekTo* self);
static void seek_to_fill_comboboxentry (SeekTo* self);
SeekTo* seek_to_new (void);
SeekTo* seek_to_construct (GType object_type);
static void seek_to_on_combobox_changed (SeekTo* self);
static void seek_to_ok_clicked (SeekTo* self);
static void seek_to_on_response (SeekTo* self, GtkDialog* source, gint response_id);
static gint seek_to_main (char** args, int args_length1);
static void _seek_to_on_response_gtk_dialog_response (SeekTo* _sender, gint response_id, gpointer self);
static void _gtk_main_quit_gtk_object_destroy (SeekTo* _sender, gpointer self);
static void _lambda0_ (GtkComboBoxEntry* target, SeekTo* self);
static void __lambda0__gtk_combo_box_changed (GtkComboBoxEntry* _sender, gpointer self);
static GObject * seek_to_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void seek_to_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);



static void _g_list_free_g_free (GList* self) {
	g_list_foreach (self, (GFunc) g_free, NULL);
	g_list_free (self);
}


SeekTo* seek_to_construct (GType object_type) {
	SeekTo * self;
	char* _tmp0_;
	self = g_object_newv (object_type, 0, NULL);
	gtk_dialog_add_button ((GtkDialog*) self, GTK_STOCK_CANCEL, (gint) GTK_RESPONSE_CANCEL);
	gtk_dialog_add_button ((GtkDialog*) self, GTK_STOCK_OK, (gint) GTK_RESPONSE_OK);
	self->priv->selected = (_tmp0_ = g_strdup (""), _g_free0 (self->priv->selected), _tmp0_);
	seek_to_init_variables (self);
	seek_to_fill_comboboxentry (self);
	return self;
}


SeekTo* seek_to_new (void) {
	return seek_to_construct (TYPE_SEEK_TO);
}


static void seek_to_init_variables (SeekTo* self) {
	GError * _inner_error_;
	GList* _tmp0_;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	self->priv->variables = (_tmp0_ = NULL, __g_list_free_g_free0 (self->priv->variables), _tmp0_);
	{
		GFile* file;
		GFileInputStream* _tmp1_;
		GFileInputStream* _tmp2_;
		GDataInputStream* _tmp3_;
		GDataInputStream* in_stream;
		char* line;
		file = g_file_new_for_path ("/tmp/.radare_flags");
		_tmp1_ = g_file_read (file, NULL, &_inner_error_);
		if (_inner_error_ != NULL) {
			_g_object_unref0 (file);
			goto __catch0_g_error;
			goto __finally0;
		}
		in_stream = (_tmp3_ = g_data_input_stream_new ((GInputStream*) (_tmp2_ = _tmp1_)), _g_object_unref0 (_tmp2_), _tmp3_);
		line = NULL;
		while (TRUE) {
			const char* _tmp4_;
			char* _tmp5_;
			char** _tmp7_;
			gint arr_size;
			gint arr_length1;
			char** _tmp6_;
			char** arr;
			_tmp4_ = g_data_input_stream_read_line (in_stream, NULL, NULL, &_inner_error_);
			if (_inner_error_ != NULL) {
				_g_object_unref0 (file);
				_g_object_unref0 (in_stream);
				_g_free0 (line);
				goto __catch0_g_error;
				goto __finally0;
			}
			if (!((line = (_tmp5_ = g_strdup (_tmp4_), _g_free0 (line), _tmp5_)) != NULL)) {
				break;
			}
			arr = (_tmp7_ = _tmp6_ = g_regex_split_simple (" ", line, 0, 0), arr_length1 = _vala_array_length (_tmp6_), arr_size = arr_length1, _tmp7_);
			self->priv->variables = g_list_append (self->priv->variables, g_strdup (arr[2]));
			arr = (_vala_array_free (arr, arr_length1, (GDestroyNotify) g_free), NULL);
		}
		_g_object_unref0 (file);
		_g_object_unref0 (in_stream);
		_g_free0 (line);
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			fprintf (stderr, "Error: %s\n", e->message);
			fprintf (stderr, "File: '/tmp/.radare_flags'!\n");
			_g_error_free0 (e);
		}
	}
	__finally0:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
		g_clear_error (&_inner_error_);
		return;
	}
	self->priv->variables = g_list_sort (self->priv->variables, strcmp);
}


static void seek_to_fill_comboboxentry (SeekTo* self) {
	g_return_if_fail (self != NULL);
	{
		GList* x_collection;
		GList* x_it;
		x_collection = self->priv->variables;
		for (x_it = x_collection; x_it != NULL; x_it = x_it->next) {
			char* x;
			x = g_strdup ((const char*) x_it->data);
			{
				gtk_combo_box_append_text ((GtkComboBox*) self->priv->cbe, x);
				_g_free0 (x);
			}
		}
	}
}


static void seek_to_on_combobox_changed (SeekTo* self) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->selected = (_tmp0_ = g_strdup (gtk_combo_box_get_active_text ((GtkComboBox*) self->priv->cbe)), _g_free0 (self->priv->selected), _tmp0_);
}


static void seek_to_on_response (SeekTo* self, GtkDialog* source, gint response_id) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (source != NULL);
	switch (response_id) {
		case GTK_RESPONSE_CANCEL:
		{
			gtk_object_destroy ((GtkObject*) self);
			break;
		}
		case GTK_RESPONSE_OK:
		{
			seek_to_ok_clicked (self);
			gtk_object_destroy ((GtkObject*) self);
			break;
		}
	}
}


static void seek_to_ok_clicked (SeekTo* self) {
	g_return_if_fail (self != NULL);
	fprintf (stdout, ":s %s\n", self->priv->selected);
}


static gint seek_to_main (char** args, int args_length1) {
	gint result;
	SeekTo* dialog;
	gtk_init (&args_length1, &args);
	dialog = g_object_ref_sink (seek_to_new ());
	gtk_widget_show_all ((GtkWidget*) dialog);
	gtk_main ();
	result = 0;
	_g_object_unref0 (dialog);
	return result;
}


int main (int argc, char ** argv) {
	g_type_init ();
	return seek_to_main (argv, argc);
}


static void _seek_to_on_response_gtk_dialog_response (SeekTo* _sender, gint response_id, gpointer self) {
	seek_to_on_response (self, _sender, response_id);
}


static void _gtk_main_quit_gtk_object_destroy (SeekTo* _sender, gpointer self) {
	gtk_main_quit ();
}


static void _lambda0_ (GtkComboBoxEntry* target, SeekTo* self) {
	g_return_if_fail (target != NULL);
	seek_to_on_combobox_changed (self);
}


static void __lambda0__gtk_combo_box_changed (GtkComboBoxEntry* _sender, gpointer self) {
	_lambda0_ (_sender, self);
}


static GObject * seek_to_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	SeekTo * self;
	parent_class = G_OBJECT_CLASS (seek_to_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = SEEK_TO (obj);
	{
		GtkLabel* _label0;
		GtkLabel* _tmp0_;
		GtkComboBoxEntry* _tmp1_;
		GtkVBox* _tmp2_;
		GtkVBox* _tmp3_;
		GtkVBox* _tmp4_;
		_label0 = NULL;
		_label0 = (_tmp0_ = g_object_ref_sink ((GtkLabel*) gtk_label_new_with_mnemonic ("Seek to the following variable:")), _g_object_unref0 (_label0), _tmp0_);
		self->priv->cbe = (_tmp1_ = g_object_ref_sink ((GtkComboBoxEntry*) gtk_combo_box_entry_new_text ()), _g_object_unref0 (self->priv->cbe), _tmp1_);
		gtk_window_set_title ((GtkWindow*) self, "Seek to Variable");
		gtk_dialog_set_has_separator ((GtkDialog*) self, FALSE);
		gtk_container_set_border_width ((GtkContainer*) self, (guint) 5);
		g_object_set ((GtkWindow*) self, "default-width", 300, NULL);
		g_object_set ((GtkWindow*) self, "default-height", 80, NULL);
		g_signal_connect_object ((GtkDialog*) self, "response", (GCallback) _seek_to_on_response_gtk_dialog_response, self, 0);
		g_signal_connect ((GtkObject*) self, "destroy", (GCallback) _gtk_main_quit_gtk_object_destroy, NULL);
		gtk_label_set_mnemonic_widget (_label0, (GtkWidget*) self->priv->cbe);
		gtk_box_pack_start ((GtkBox*) (_tmp2_ = ((GtkDialog*) self)->vbox, GTK_IS_VBOX (_tmp2_) ? ((GtkVBox*) _tmp2_) : NULL), (GtkWidget*) _label0, FALSE, TRUE, (guint) 0);
		g_signal_connect_object ((GtkComboBox*) self->priv->cbe, "changed", (GCallback) __lambda0__gtk_combo_box_changed, self, 0);
		gtk_box_pack_start ((GtkBox*) (_tmp3_ = ((GtkDialog*) self)->vbox, GTK_IS_VBOX (_tmp3_) ? ((GtkVBox*) _tmp3_) : NULL), (GtkWidget*) self->priv->cbe, FALSE, TRUE, (guint) 0);
		gtk_box_set_spacing ((GtkBox*) (_tmp4_ = ((GtkDialog*) self)->vbox, GTK_IS_VBOX (_tmp4_) ? ((GtkVBox*) _tmp4_) : NULL), 10);
		_g_object_unref0 (_label0);
	}
	return obj;
}


static void seek_to_class_init (SeekToClass * klass) {
	seek_to_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (SeekToPrivate));
	G_OBJECT_CLASS (klass)->constructor = seek_to_constructor;
	G_OBJECT_CLASS (klass)->finalize = seek_to_finalize;
}


static void seek_to_instance_init (SeekTo * self) {
	self->priv = SEEK_TO_GET_PRIVATE (self);
}


static void seek_to_finalize (GObject* obj) {
	SeekTo * self;
	self = SEEK_TO (obj);
	_g_object_unref0 (self->priv->cbe);
	_g_free0 (self->priv->selected);
	__g_list_free_g_free0 (self->priv->variables);
	G_OBJECT_CLASS (seek_to_parent_class)->finalize (obj);
}


GType seek_to_get_type (void) {
	static GType seek_to_type_id = 0;
	if (seek_to_type_id == 0) {
		static const GTypeInfo g_define_type_info = { sizeof (SeekToClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) seek_to_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SeekTo), 0, (GInstanceInitFunc) seek_to_instance_init, NULL };
		seek_to_type_id = g_type_register_static (GTK_TYPE_DIALOG, "SeekTo", &g_define_type_info, 0);
	}
	return seek_to_type_id;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}




